version: 2.1

executors:
  plaid-android-executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/plaid
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

  plaid-gcloud-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/plaid
    environment:
      TERM: dumb

commands:
  store-plaid-artifacts:
    description: "It stores Lint & Test artifacts"
    parameters:
      artifact-path:
        type: string
    steps:
      - store_artifacts:
          path: <<parameters.artifact-path>>

jobs:
  build:
    executor: plaid-android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Run JVM Tests & Lint, assemble app and test APKs for debug and release
          command: ./gradlew check assemble assembleAndroidTest --stacktrace
      - run:
          name: Gather Lint results
          command: scripts/copy_lint_results.sh
      - store-plaid-artifacts:
          artifact-path: ci_results/lint
      # Persist build directory for all modules
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

  test_instrumented:
    executor: plaid-gcloud-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/plaid
      - run:
          name: Setup Google Cloud auth
          command: scripts/ftl_setup.sh
      - run:
          name: Run tests on Firebase Test Lab and download results
          command: scripts/ftl_run_tests.sh $CIRCLE_BUILD_NUM firebase_test_results
          when: always
      - store-plaid-artifacts:
          artifact-path: firebase_test_results
      - store_test_results:
          path: firebase_test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_instrumented:
          requires:
            - build
